[versions]
# https://plugins.jetbrains.com/docs/intellij/using-kotlin.html#kotlin-standard-library
kotlin = "2.2.20"
# https://www.jetbrains.com/intellij-repository/snapshots/com/jetbrains/intellij/rider/riderRD/maven-metadata.xml
# https://www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/rider/riderRD/maven-metadata.xml
ideaSdk = "2025.3"
riderSdk = "2026.1-SNAPSHOT"

[libraries]
kotlinStdLib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
openTest4J = "org.opentest4j:opentest4j:1.3.0"
jflex = "de.jflex:jflex:1.9.1"

[plugins]
grammarkit = "org.jetbrains.grammarkit:2022.3.2.2"
changelog = "org.jetbrains.changelog:2.2.1"
gradleIntelliJPlatform = "org.jetbrains.intellij.platform:2.9.0"
gradleJvmWrapper = "me.filippov.gradle.jvm.wrapper:0.14.0"
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
