[versions]
# https://plugins.jetbrains.com/docs/intellij/using-kotlin.html#kotlin-standard-library
kotlin = "2.1.20"
# https://www.jetbrains.com/intellij-repository/snapshots/com/jetbrains/intellij/rider/riderRD/maven-metadata.xml
# https://www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/rider/riderRD/maven-metadata.xml
ideaSdk = "252-EAP-SNAPSHOT"
riderSdk = "2025.3-SNAPSHOT"

[libraries]
kotlinStdLib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }

[plugins]
gradleIntelliJPlatform = "org.jetbrains.intellij.platform:2.7.0"
gradleJvmWrapper = "me.filippov.gradle.jvm.wrapper:0.14.0"
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
